# Site settings
title: Michael Shum
email: petriomelony@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Michael Shum, Mechanical Engineering Graduate and
  Ontario Certified Teacher.  Experienced STEM Educator with a passion
  for building things, gaming, and music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://petriomelony.github.io" # the base hostname & protocol for your site

twitter_username: petriomelony
github_username: petriomelony

# Build settings
markdown: kramdown